### ISSUE TITLE
jquery.filterizr.min.js:1 Uncaught TypeError: Cannot read property 'outerWidth' of undefined

### ISSUE THREAD

**Issue by danielnaxon-inmanage** [giotiskl/Filterizr#26] opened 2016-07-13 14:53 UTC
Hi,

I'm getting the above error straight as the page loads. In addition, every time I click a filter button I get the following one:
jquery.filterizr.min.js:1 Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by giotiskl** [comment] 2016-07-13 14:54
can you provide your html?

**Comment by CharlyPoppins** [comment] 2016-07-20 11:44
Seems it happens when filtering on a category that does not contain any items.

**Comment by Stromwerk** [comment] 2016-07-29 13:10
I am having the same issue. [Here](/http://codepen.io/anon/pen/BzPzXm) is an example codepen.

**Comment by TaffoVelikoff** [comment] 2016-07-30 18:55
I don't know if you finally found a fix for this, but I had the same problem. I am a back end developer and not really skilled with jquery/javascript, but I did managed to fix the problem with this simple solution:

1. Open jquery.fiterizr.js
2. Scroll to line 705 (_handleFiltering: function(target))
3. Add this code in the beginning of the function
if(!target){
  var target = 0; 
}

The filter works fine for me now. Maybe somebody can share a better way to fix this.

![filterizrfix](https://cloud.githubusercontent.com/assets/20744689/17272497/33c5128e-56a0-11e6-890e-32b7487dda6a.png)

**Comment by slavap** [comment] 2016-08-09 19:33
I've got the same error when used: $(myContainerElt).filterizr();
For me the fix was using text selector: $(".filtr-container").filterizr();

**Comment by mesterica** [comment] 2016-08-09 21:35
Mi also not really skilled with jquery/javascript but I have found one thing (maybe someone can solve it).
So in mi case the problem is the version of jQuery 
With jQuery 3.1.0 I have the same error but with jQuery 2.1.1 working good

**Comment by slavap** [comment] 2016-08-10 00:40
Yes, that's correct, jquery .selector was removed in version 3.0, so your explanation looks right.
https://api.jquery.com/selector/

**Comment by bmikol** [comment] 2017-05-24 16:48
I came across this too; unfortunately @TaffoVelikoff's fix didn't work for me. Got around it by backing down from jQuery 3.2.1 to 2.2.4 (and backing out the fix).

**Comment by giotiskl** [comment] 2017-05-26 11:28
Closed with #50

**Closed by giotiskl** 2017-05-26 11:28 UTC

**Comment by sumon380** [comment] 2017-11-28 15:52
Just solved the problem using class "filtr-item" to the gallery item. I hope this will help you too
