### ISSUE TITLE
can i exclude all button in that??

### ISSUE THREAD

**Issue by rajkvx** [giotiskl/Filterizr#7] opened 2016-04-24 19:26 UTC
Nice Plugin. Great Job.

Only thing i found is - 
When i am excluding all button from the filter menu, than it should not show all the items on page!! It should show as per the #no. given in data-filter attribute.

Can you solve this?

**Comment by giotiskl** [comment] 2016-04-24 19:38
@rajkvx if I understood correctly, you want to initialize Filterizr right into the 1st category (not having all items show up at first?) if so all you need to do is exclude the all button and pass in an option when initializing filter like this:
````
$('.filtr-container').filterizr({filter: 1});
````
instead of ````$('.filtr-container').filterizr();````

**Comment by rajkvx** [comment] 2016-04-24 19:42
Cool that worked. Seems you made all way great!!

Again great piece of work!!

**Comment by giotiskl** [comment] 2016-04-24 19:44
Glad to see you enjoy Filterizr, I would appreciate it if you could star the repository. This way you'll be kept posted of future updates as well.

Since the issue is resolved, I'll be closing this!

**Closed by giotiskl** 2016-04-24 19:44 UTC
