### ISSUE TITLE
dimensions cannot be recognized if there were in percentage

### ISSUE THREAD

**Issue by hoomb** [giotiskl/Filterizr#5] opened 2016-04-14 15:30 UTC
The Plugin doesn't show items correctly at the beginning if I use percentage as container or item width.

My code is like this:

```
.filtr-container {
  width: 100%;
}

.filtr-item {
  background-color: #e1e1e1;
  color: #7f8c8d;
  border: 1px solid #fff;
  padding: 20px;
}

<div class="filtr-container">
   <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="1">TEXT</div>
</div>
```

I initialize the plugin on window.load (document.ready has the same effect).

The Problem is width: 100% in filtr-container will be handled as "100" and "col-md-3" handled as "25" and not "25%"

Debugging your code on "_calcItemPositions" method shows these values:

containerHeight = 0,
            cols = Math.round(self.width() / self.find('.filtr-item').outerWidth()),  ---> self.width() => 100 !!
            rows = 0,
            //Item data
            itemWidth  = array[0].outerWidth(),    => itemWidth => 25 !!

**Comment by giotiskl** [comment] 2016-04-14 17:56
@hoomb I dont seem to be able to reproduce your problem, here is what happens for me:

at 100% width:
![100percent](https://cloud.githubusercontent.com/assets/12873414/14538188/20310410-0283-11e6-9619-04495ec4baf0.jpg)

at 50% width things normally scale down and look well:
![50percent](https://cloud.githubusercontent.com/assets/12873414/14538202/34a8a3d0-0283-11e6-9d38-71ba3c2d9b79.jpg)

could you elaborate on what the problem is? In what sense do the items no show correctly? Perhaps a screenshot could help me to visualise the problem.

**Comment by hoomb** [comment] 2016-04-15 12:44
Thank you for your response. I have found the Problem. The .filtr-container was under a Tab which has been initialized first on selecting it. This Code has fixed the problem:

```
  $('a[href="#tab-2"]').on('shown.bs.tab', function (e) {
    $('.filtr-container').filterizr();
  });  
```

**Comment by giotiskl** [comment] 2016-04-15 13:32
@Glad to see the problem was elsewhere, I am thus closing this issue. If you wish your project to be featured on Filterizr's website, make sure to email me!

**Closed by giotiskl** 2016-04-15 13:32 UTC
